apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-service
  template:
    metadata:
      labels:
        app: spring-service
    spec:
      containers:
        - name: backend
          image: devops/backend:1 # le tag sera mis à jour par le CI
          ports:
            - containerPort: 8283
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/devopsdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          readinessProbe:
            tcpSocket:
              port: 8283
            initialDelaySeconds: 20
