apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: spring-service
  ports:
    - port: 8282
      targetPort: 8283
      nodePort: 30082
